# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Clolder.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os, time


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(289, 184)
        Form.setStyleSheet("background-color: #dec5b1;")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: white;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(50, 80, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #ded4b1;\n"
"border: 2px solid black;")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 150, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(230, 170, 55, 13))
        self.label_2.setStyleSheet("color: gray;")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cloder"))
        Form.setWindowIcon(QtGui.QIcon("dist/logo.ico"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter direction of folder"))
        self.pushButton.setText(_translate("Form", "Sort"))
        self.label_2.setText(_translate("Form", "JJpon corp."))

    def sort(self):
        dir = self.lineEdit.text()
        try:
            content = os.listdir(dir)
            for i in content:
                os.chdir(dir)
                dotted = i.split('.')
                try:
                    if dotted[0] and dotted[-1]:
                            os.mkdir(str(dotted[-1]))
                except:
                    pass
            self.label.setText('Folders created...')

            for i in content:
                dotted = i.split('.')
                if dotted[0]:
                    try:
                        os.rename(f'{dir}\\{i}', f'{dir}\\{dotted[-1]}\\{i}')
                    except IndexError:
                        pass
            self.label.setText('files successfully moved!')
        except:
            self.label.setText('Error try again')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    ui.pushButton.clicked.connect(ui.sort)
    sys.exit(app.exec_())
